# Generated by Django 3.0.3 on 2020-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('anada', models.CharField(max_length=4)),
                ('denominacion', models.CharField(max_length=50)),
                ('bodega', models.CharField(max_length=50)),
                ('puntuacion', models.CharField(max_length=4)),
                ('maridaje', models.TextField()),
                ('vista', models.TextField()),
                ('nariz', models.TextField()),
                ('boca', models.TextField()),
                ('imagen', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
