# Generated by Django 3.0.3 on 2020-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVinos', '0005_auto_20200328_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinos',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
