# Generated by Django 3.0.3 on 2020-04-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVinos', '0006_vinos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinos',
            name='puntos',
            field=models.TextField(),
        ),
    ]
