# Generated by Django 3.0.3 on 2020-04-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVinos', '0008_auto_20200407_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinos',
            name='anada',
            field=models.IntegerField(),
        ),
    ]
