# Generated by Django 3.0.3 on 2020-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVinos', '0009_auto_20200407_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinos',
            name='anada',
            field=models.CharField(max_length=10),
        ),
    ]
