# Generated by Django 3.0.3 on 2020-04-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVinos', '0010_auto_20200409_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinos',
            name='anada',
            field=models.IntegerField(),
        ),
    ]
